jobs:
  build:
    if: needs.prepare_jobs.outputs.pr_found == 'false' || github.event_name == 'pull_request'
    name: Build
    needs: prepare_jobs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout git repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      name: Upload code coverage
      uses: codecov/codecov-action@v4.0.0-beta.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      env:
        GPG_KEY_NAME: B70E1EAC
        GPG_PASSPHRASE_FILE: ${{ secrets.GPG_PASSPHRASE_FILE }}
        GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      if: startsWith(github.ref, 'refs/tags/') && matrix.java == 11
      name: Release
      run: './ci/before-deploy.sh

        cp ./ci/.m2.settings.xml $HOME/.m2/settings.xml

        mvn deploy -P release -DskipTests=true

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/') && matrix.java == 11
      name: Create release
      run: npx changelogithub
    strategy:
      matrix:
        java:
        - '11'
        - '21'
  prepare_jobs:
    name: 'Prepare: job optimization'
    outputs:
      pr_found: ${{ steps.pr.outputs.pr_found }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: pr
      name: Get current PR
      uses: 8BitJonny/gh-get-current-pr@3.0.0
      with:
        filterOutClosed: true
        sha: ${{ github.event.pull_request.head.sha }}
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
